name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest]
        os: [ubuntu-latest]
        # node-version: [8.x, 10.x, 12.x]
        node-version: [8.x]
        python-version: [3.x]
        java-version: [9.0.4]
    
    steps:
    - name: checkout code
      uses: actions/checkout@v1

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }} 
        architecture: 'x64' # (x64 or x86)

    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
        architecture: x64 // (x64 or x86) - defaults to x64

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        # npm ci
        npm install -g react-native-cli
        npm run build --if-present
        # npm test
        # react-native run-android
        gem install xcode-install
      env:
        CI: true
